=== foundeo/cfdocs/data/cfdocs.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "engineDetail": {
      "title": "Engine Detail",
      "type": "object",
      "properties": {
        "minimum_version": {
          "title": "Minimum version",
          "description": "The version of the engine in which this was introduced",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$"
        },
        "deprecated": {
          "title": "Deprecated version",
          "description": "The version of the engine in which this was deprecated",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "removed": {
          "title": "Removed version",
          "description": "The version of the engine in which this was removed",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "notes": {
          "title": "Notes",
          "description": "Additional notes about engine compatibility",
          "type": "string",
          "default": ""
        },
        "docs": {
          "title": "Docs",
          "description": "Link to engine-specific documentation",
          "type": "string",
          "default": ""
        }
      },
      "required": [
        "minimum_version"
      ]
    },
    "engines": {
      "title": "Engines",
      "type": "object",
      "properties": {
        "coldfusion": {
          "title": "ColdFusion",
          "description": "Engine details for ColdFusion",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "railo": {
          "title": "Railo",
          "description": "Engine details for Railo",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "lucee": {
          "title": "Lucee",
          "description": "Engine details for Lucee",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "openbd": {
          "title": "OpenBD",
          "description": "Engine details for OpenBD",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "boxlang": {
          "title": "BoxLang",
          "description": "Engine details for BoxLang",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "rustcfml": {
          "title": "RustCFML",
          "description": "Engine details for RustCFML",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        }
      }
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Parameter",
        "description": "Argument or attribute",
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "description": "Parameter name",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the parameter",
            "type": "string"
          },
          "type": {
            "title": "Type",
            "description": "The data type of the parameter",
            "type": "string",
            "enum": [
              "any",
              "array",
              "binary",
              "boolean",
              "component",
              "date",
              "function",
              "guid",
              "numeric",
              "query",
              "string",
              "struct",
              "uuid",
              "variableName",
              "xml"
            ]
          },
          "required": {
            "title": "Required",
            "description": "Whether this parameter is required",
            "type": "boolean"
          },
          "default": {
            "title": "Default",
            "description": "The default value of the parameter when not provided",
            "type": ["string", "boolean", "number"],
            "default": ""
          },
          "values": {
            "title": "Values",
            "description": "List of enumerated values for the parameter",
            "type": "array",
            "minItems": 0,
            "items": {
              "title": "Value",
              "description": "One of the enumerated values for the parameter",
              "type": ["string", "boolean", "number"]
            },
            "default": []
          },
          "engines": {
            "title": "Engines",
            "description": "Engine compatibility information",
            "type": "object",
            "$ref": "#/definitions/engines"
          },
          "callback_params": {
            "title": "Callback Parameters",
            "description": "When type is function, this represents the parameters for the callback",
            "type": "array",
            "$ref": "#/definitions/params",
            "minItems": 0,
            "default": []
          }
        },
        "required": [
          "name",
          "description",
          "type",
          "required"
        ]
      },
      "default": []
    }
  },
  "title": "CFDocs",
  "description": "CFDocs data file",
  "type": "object",
  "properties": {
    "name": {
      "title": "Name",
      "description": "The name of the tag or function. Start with lowercase, except Application.cfc.",
      "type": "string",
      "pattern": "^([a-zA-Z0-9 \\./_-]+)$"
    },
    "description": {
      "title": "Description",
      "description": "A short description of the item",
      "type": "string"
    },
    "type": {
      "title": "Type",
      "description": "Whether this refers to a function, tag, or listing",
      "type": "string",
      "enum": [
        "function",
        "tag",
        "listing",
        "component"
      ]
    },
    "syntax": {
      "title": "Syntax",
      "description": "The basic syntax of the tag or function",
      "type": "string",
      "default": ""
    },
    "script": {
      "title": "Syntax",
      "description": "For tags, shows how the tag would be invoked from cfscript.",
      "type": "string",
      "default": ""
    },
    "member": {
      "title": "Member",
      "description": "Deprecated. For functions, shows the available member function syntax.",
      "type": "string",
      "default": ""
    },
    "member_details": {
      "title": "Member Details",
      "description": "For details of the member function equivalent of this function.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the member function. Start with lowercase.",
          "type": "string",
          "pattern": "^[a-z]\\w+$"
        },
        "type": {
          "title": "Type",
          "description": "The data type for which this function is a member",
          "type": "string",
          "enum": [
            "array",
            "boolean",
            "date",
            "image",
            "locale",
            "query",
            "string",
            "struct",
            "spreadsheet",
            "xml"
          ]
        },
        "returns": {
          "title": "Return Type",
          "description": "The return type of the member function.",
          "type": "string",
          "enum": [
            "any",
            "array",
            "binary",
            "boolean",
            "date",
            "function",
            "guid",
            "numeric",
            "query",
            "string",
            "struct",
            "uuid",
            "variableName",
            "void",
            "xml"
          ],
          "default": "void"
        },
        "engines": {
          "title": "Engines",
          "description": "Engine compatibility information",
          "type": "object",
          "$ref": "#/definitions/engines"
        },
        "base_param_index": {
          "title": "Base Param Index",
          "description": "A 1-based index referencing the param on which the member function is based",
          "type": "number",
          "default": 1
        }
      },
      "required": [
        "name",
        "type",
        "returns"
      ]
    },
    "returns": {
      "title": "Return Type",
      "description": "The return type of a function",
      "type": "string",
      "enum": [
        "any",
        "array",
        "binary",
        "boolean",
        "date",
        "function",
        "guid",
        "numeric",
        "query",
        "string",
        "struct",
        "uuid",
        "variableName",
        "void",
        "xml"
      ],
      "default": "void"
    },
    "related": {
      "title": "Related",
      "description": "A list of tag or function names that are related to this item",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Entity name",
        "description": "The name of a function or tag that is already documented",
        "type": "string"
      },
      "default": []
    },
    "discouraged": {
      "title": "Discouraged",
      "description": "If this key exists and has content a warning is displayed stating that the tag or function is discouraged by the CFML community.",
      "type": "string",
      "default": ""
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "$ref": "#/definitions/params",
      "minItems": 0,
      "default": []
    },
    "engines": {
      "title": "Engines",
      "description": "Engine compatibility information",
      "type": "object",
      "$ref": "#/definitions/engines"
    },
    "links": {
      "title": "Links",
      "description": "A list of external references",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Link",
        "description": "Information about the reference",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "A title for the link",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "A description for the link",
            "type": "string"
          },
          "url": {
            "title": "URL",
            "description": "The link URL",
            "type": "string"
          }
        },
        "required": [
          "title",
          "description",
          "url"
        ]
      },
      "default": []
    },
    "examples": {
      "title": "Examples",
      "description": "A list of examples",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Example",
        "description": "Information about the example",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "Name of the code example",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the code example",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "description": "The example code",
            "type": "string"
          },
          "result": {
            "title": "Result",
            "description": "The expected output of the code example",
            "type": ["string", "boolean", "number"]
          },
          "runnable": {
            "title": "Runnable",
            "description": "Whether the code is runnable (in trycf for example)",
            "type": "boolean",
            "default": true
          },
          "testable": {
            "title":"Testable",
            "description": "If the example can be tested. May need to set to false if there is a bug on certain engines.",
            "type": "boolean",
            "default": true
          }
        },
        "required": [
          "title",
          "description",
          "code"
        ]
      },
      "default": []
    }
  },
  "required": [
    "name",
    "description",
    "type"
  ]
}

=== foundeo/cfdocs/data/en/pdftoimage.json
{
	"name":"pdfToImage",
	"type":"function",
	"syntax":"pdfToImage(pdfObj [, page [, width [, dpi]]])",
	"returns":"any",
	"related":["pdfRead","pdfInfo","pdfPageCount","imageWrite"],
	"description":"Rasterises a 1-based page of a PDF into an ordinary image object, so the whole image* family (resize, crop, watermark, write in any format) applies to the result. width wins if given; otherwise dpi is used (PDF's native resolution is 72dpi, so dpi/72 is the scale); otherwise 1:1. The output canvas is capped at 40 megapixels regardless of what the page declares — if exceeded, the scale is reduced to fit rather than the call failing.",
	"params": [
		{"name":"pdfObj","description":"A PDF object from pdfRead() or pdf().","required":true,"default":"","type":"any","values":[]},
		{"name":"page","description":"1-based page number to render.","required":false,"default":"1","type":"numeric","values":[]},
		{"name":"width","description":"Target width of the rendered image in pixels. Wins over dpi when given.","required":false,"default":"","type":"numeric","values":[]},
		{"name":"dpi","description":"Target resolution in DPI. Used when width is not given (scale = dpi / 72).","required":false,"default":"","type":"numeric","values":[]}
	],
	"engines": {
		"rustcfml": {"minimum_version": ""}
	},
	"links": [],
	"examples": [
		{
			"title":"Render page 1 to a 400px-wide PNG",
			"description":"Rasterise the first page and write it to disk.",
			"code":"doc = PdfRead( expandPath( \"/invoice.pdf\" ) );\nimg = PdfToImage( doc, 1, 400 );\nimageWrite( img, expandPath( \"/thumb.png\" ) );"
		}
	]
}

=== foundeo/cfdocs/data/en/cfcache.json
{
	"name":"cfcache",
	"type":"tag",
	"syntax":"<cfcache>",
	"related":[],
	"description":"Stores a copy of a page on the server and/or client computer,\n to improve page rendering performance. To do this, the tag\n creates temporary files that contain the static HTML returned\n from a CFML page.\n\n Use this tag if it is not necessary to get dynamic content each\n time a user accesses a page.\n You can use this tag for simple URLs and for URLs that contain\n URL parameters.",
	"params": [
		{"name":"action","description":"* cache: server-side and client-side caching.\n * flush: refresh cached page(s).\n * clientcache: browser-side caching only. To cache a personalized page, use this option.\n * servercache: server-side caching only. Not recommended.\n * optimal: same as \"cache\".","required":false,"default":"","type":"string","values":["cache","flush","clientcache","servercache","optimal","get","put"]},
		{"name":"directory","description":"Absolute path of cache directory.","required":false,"default":"","type":"string","values":[]},
		{"name":"timespan","description":"The interval until the page is flushed from the cache.","required":false,"default":"","type":"numeric","values":[]},
		{"name":"expireurl","description":"Used with action = \"flush\". A URL reference. CFML\n matches it against the mappings in the specified cache\n directory. Can include wildcards. For example:\n \"*\/view.cfm?id=*\".","required":false,"default":"","type":"string","values":[]},
		{"name":"username","description":"A username","required":false,"default":"","type":"string","values":[]},
		{"name":"password","description":"A password","required":false,"default":"","type":"string","values":[]},
		{"name":"port","description":"Remote port to which to connect","required":false,"default":"","type":"numeric","values":[]},
		{"name":"protocol","description":"Protocol that is used to create URL from cache.","required":false,"default":"","type":"string","values":["http:\/\/","https:\/\/"]},
		{"name":"value","description":"For action=\"set\", object which needs to be stored","required":false,"default":"","type":"string","values":[]},
		{"name":"metadata","description":"Name of the struct variable","required":false,"default":"","type":"string","values":[]},
		{"name":"stripwhitespace","description":"Reduces whitespace","required":false,"default":false,"type":"boolean","values":[true,false]},
		{"name":"throwonerror","description":"A Boolean value specifying whether to throw an error if the\nflush action encounters an error. Otherwise the action does not\ngenerate an error if it fails. If this attribute is 'true' you can handle the\nerror in a cfcatch block, for example, if a specified id value is invalid","required":false,"default":"","type":"boolean","values":[]},
		{"name":"id","description":"Id of the cached object","required":false,"default":"","type":"string","values":[]},
		{"name":"key","description":"key to access cache","required":false,"default":"","type":"string","values":[]},
		{"name":"usecache","description":"to use cache or not (if false it will process the content each time)","required":false,"default":true,"type":"boolean","values":[true,false]},
		{"name":"dependson","description":"Comma separated list of all variables on which this cache would depend","required":false,"default":"","type":"string","values":[]},
		{"name":"idletime","description":"Flushes the cached item if it is not accessed for the specified time span.","required":false,"default":"","type":"numeric","values":[]},
		{"name":"cachedirectory","description":"Cache directory","required":false,"default":"","type":"string","values":[]},
		{"name":"name","description":"name of return variable, valid with action=\"get\"","required":false,"default":"","type":"string","values":[]}

	],
	"engines": {
		"coldfusion": {"minimum_version":"4", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-c/cfcache.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/tags/cache.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/tag/cfcache"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/tag/cfcache"},
		"boxlang": {"minimum_version":"1.0.0", "notes":"`<bx:cache>` in BoxLang files", "docs":"https://boxlang.ortusbooks.com/boxlang-language/reference/components/cache/cache"},
		"rustcfml": {"minimum_version": "", "notes": "Cache-level maxObjects/evictionPolicy not applied (per-entry TTL works)."}
	},
	"links": [

	],
	"examples": [
		{
			"title":"Adding a page to the cache",
			"code":"<cfcache action='optimal' directory='/path/to/directory' timespan='#createTimeSpan( 1, 0, 0, 0 )#' idletime='#createTimeSpan( 0, 12, 0, 0 )#'>\n\t<div id=\"some-id\">Hello World!</div>\n</cfcache>",
			"description":"Puts HTML page into the cache and uses the cached version on subsequent calls to the page.",
			"result":"<div id=\"some-id\">Hello World!</div>"
		},
		{
			"title":"Flushing a page from the cache",
			"code":"<cfcache action='flush' directory='/path/to/directory' expireURL='/hello-world.cfm'></cfcache>",
			"description":"Flushes the 'hello-world.cfm' page from the cache.",
			"result":""
		}
	]

}

=== foundeo/cfdocs/data/en/getwriteableimageformats.json
{
	"name":"getWriteableImageFormats",
	"type":"function",
	"syntax":"getWriteableImageFormats()",
	"returns":"string",
	"related":[],
	"description":"Returns a list of image formats that ColdFusion can write on the operating system where ColdFusion is deployed.",
	"params": [],
	"engines": {
		"coldfusion": {"minimum_version":"8", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-e-g/getwriteableimageformats.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/getwriteableimageformats.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/getwriteableimageformats"},
		"boxlang": {"minimum_version":"1.0.0", "notes":"Requires the `bx-image` module.", "docs":"https://boxlang.ortusbooks.com/boxlang-framework/modularity/image-manipulation"},
		"rustcfml": {"minimum_version": ""}
	},
	"links": []
}

=== foundeo/cfdocs/data/en/s3listbuckets.json
{
	"name":"s3ListBuckets",
	"type":"function",
	"syntax":"s3ListBuckets([accessKeyId, secretKey, host])",
	"returns":"array",
	"related":["s3listbucket","s3createbucket","s3delete"],
	"description":"Lists all buckets accessible with the resolved credentials. Returns an array of structs with bucketName and creationDate.",
	"params": [
		{"name":"accessKeyId","description":"Inline AWS access key id. Overrides credentials from Application.cfc and environment variables.","required":false,"default":"","type":"string","values":[]},
		{"name":"secretKey","description":"Inline AWS secret access key.","required":false,"default":"","type":"string","values":[]},
		{"name":"host","description":"Inline endpoint URL for S3-compatible providers (e.g. Cloudflare R2, MinIO).","required":false,"default":"","type":"string","values":[]}
	],
	"engines": {
		"rustcfml": {"minimum_version": ""}
	},
	"links": [],
	"examples": [
		{
			"title": "List all buckets",
			"description": "Returns an array of bucket structs.",
			"code": "buckets = s3ListBuckets();",
			"result": "",
			"runnable":false
		}
	]
}

=== foundeo/cfdocs/data/en/soundex.json
{
	"name": "soundEx",
	"type": "function",
	"syntax": "soundEx(str)",
	"returns": "string",
	"related": ["metaphone"],
	"description": "Soundex is a phonetic algorithm for indexing names by sound, as pronounced in English.\nThe goal is for homophones to be encoded to the same representation so that they can be matched despite minor differences in spelling.\nThe algorithm mainly encodes consonants; a vowel will not be encoded unless it is the first letter.\n\nSoundex is the most widely known of all phonetic algorithms, as it is a standard feature of MS SQL and Oracle, and is often used (incorrectly) as a synonym for 'phonetic algorithm'",
	"params": [
		{"name": "str", "description": "", "required": true, "default": "", "type": "string", "values": []}
	],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "https://docs.lucee.org/reference/functions/soundex.html"},
		"rustcfml": {"minimum_version": ""}
	},
	"links": [],
	"examples": [{
		"title":"Get Soundexes of \"Robert\", \"Rupert\" and \"Rubin\"",
		"description":"Both \"Robert\" and \"Rupert\" return the same string \"R163\" while \"Rubin\" yields \"R150\"",
		"code":"soundEx(\"Robert\")&\"/\"&soundEx(\"Rupert\")&\"/\"&soundEx(\"Rubin\")",
		"result":"R163/R163/R150",
		"runnable": true
	}]
}

=== foundeo/cfdocs/data/en/s3upload.json
{
	"name":"s3Upload",
	"type":"function",
	"syntax":"s3Upload(bucket, object, source [, acl, location, accessKeyId, secretKey, host])",
	"returns":"void",
	"related":["s3write","s3read"],
	"description":"Uploads a local file to an S3 (or S3-compatible) bucket. The MIME type is auto-detected from the object key extension.",
	"params": [
		{"name":"bucket","description":"The name of the S3 bucket to upload to.","required":true,"default":"","type":"string","values":[]},
		{"name":"object","description":"The object key to write.","required":true,"default":"","type":"string","values":[]},
		{"name":"source","description":"Path of the local file to upload.","required":true,"default":"","type":"string","values":[]},
		{"name":"acl","description":"Object ACL to apply (accepted for compatibility; not enforced).","required":false,"default":"","type":"string","values":[]},
		{"name":"location","description":"Bucket location/region (accepted for compatibility).","required":false,"default":"","type":"string","values":[]},
		{"name":"accessKeyId","description":"Inline AWS access key id. Overrides credentials from Application.cfc and environment variables.","required":false,"default":"","type":"string","values":[]},
		{"name":"secretKey","description":"Inline AWS secret access key.","required":false,"default":"","type":"string","values":[]},
		{"name":"host","description":"Inline endpoint URL for S3-compatible providers (e.g. Cloudflare R2, MinIO).","required":false,"default":"","type":"string","values":[]}
	],
	"engines": {
		"rustcfml": {"minimum_version": ""}
	},
	"links": [],
	"examples": [
		{
			"title": "Upload a local file",
			"description": "Reads the local file and stores it in the bucket.",
			"code": "s3Upload(\"my-bucket\", \"uploads/report.pdf\", expandPath(\"./report.pdf\"));",
			"result": "",
			"runnable":false
		}
	]
}

=== foundeo/cfdocs/data/en/imagefiltercurves.json
{
	"name": "imageFilterCurves",
	"type": "function",
	"syntax": "imageFilterCurves()",
	"returns": "any",
	"related": ["imageFilterColorMap","imageFilter","imageFilterKernel","imageFilterWarpGrid"],
	"description": "",
	"params": [],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "https://docs.lucee.org/reference/functions/imagefiltercurves.html"}
	},
	"examples": [],
	"links": []
}

=== foundeo/cfdocs/data/en/arrayresize.json
{
	"name":"arrayResize",
	"type":"function",
	"syntax":"arrayResize(array, size)",
	"member":"someArray.resize(size)",
	"returns":"boolean",
	"related":[],
	"description":"Resets an array to a specified minimum number of elements.\n This can improve performance, if used to size an array to its\n expected maximum. For more than 500 elements, use arrayResize\n immediately after using the ArrayNew tag.",
	"params": [
		{"name":"array","description":"","required":true,"default":"","type":"array","values":[]},
		{"name":"size","description":"","required":true,"default":"","type":"numeric","values":[]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"3", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-a-b/arrayresize.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/arrayresize.html"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/arrayresize"},
		"boxlang": {"minimum_version":"1.0.0", "notes":"", "docs":"https://boxlang.ortusbooks.com/boxlang-language/reference/built-in-functions/array/arrayresize"},
		"rustcfml": {"minimum_version": ""}
	},
	"links": [
		{
		"title":"Learning Built-In Functions And Member-Methods by Ben Nadel",
		"description":"",
		"url":"https://www.bennadel.com/blog/3813-built-in-functions-and-member-methods-return-different-data-types-in-lucee-cfml-5-3-5-92.htm"
		}
	],
	"examples": [
		{
			"title": "Tag Syntax",
			"description": "",
			"code": "<cfset MyArray = arrayNew(1)> \r\n <!--- Resize that array to the number of records in the query. ---> \r\n <cfset temp = arrayResize(MyArray, 8)> \r\n  <cfdump var=\"#MyArray#\" />  ",
			"result": ""
		}
	]

}
